- id: terraform_inputs_jenkins_pipeline_params
  name: Terraform Inputs from/to Jenkins Pipeline Parameters
  description: Supports the definition of a (declarative) Jenkins Pipeline's parameters from your Terraform Input Variables. Also supports the creation of a terraform.tfvars.json file based on your Terraform Input Variables, with values provided by the Jenkins Pipeline parameters' arguments. Requires segmentio/terraform-docs >= v0.4.0.
  entry: terraform_inputs_jenkins_pipeline_params
  language: python
  files: (\.tf)$
  exclude: \.terraform\/.*$
  minimum_pre_commit_version: 0.15.0
