- id: jenkins_pipeline_from_terraform_input_vars
  name: Jenkins Pipeline Parameters from Terraform Input Variables
  description: Inserts Terraform Input Variables into the parameters directive of a Declarative Jenkins Pipeline in your project's Jenkinsfile. Additionally, it populates a JSON data structure to populate a terraform.tfvars.json file with the Jenkins Pipeline's parameter arguments. Requires segmentio/terraform-docs.
  entry: jenkins_pipeline_from_terraform_input_vars.sh
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$
